# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ADxuzk3-FgEfo43-8xYi-GZJpIxSF9E
"""

import pandas as pd
import os
from shutil import move

def arrange(output_dir,file_dir,data):
    file_list=os.listdir(file_dir)
    for id, value, in zip(data['id'],data['value']):
        path_dir=os.path.join(output_dir,str(value))
        if not os.path.exists(path_dir):
            os.makedirs(path_dir)
        file_name=str(id) + '.mat'
        if file_name in file_list:
            source_path=os.path.join(file_dir,file_name)
            destination_path=os.path.join(path_dir,file_name)
            move(source_path,destination_path)

def label_generation(output_dir):
    output=os.listdir(output_dir)
    files_path=[]
    labels=[]
    class_name={'~':0,'A':1,'N':2,'O':3}
    for class_folder in output:
        file_name=os.path.join(output_dir,class_folder)
        if os.path.isdir(file_name):
            for files in os.listdir(file_name):
                if files.endswith('.mat'):
                    files_path.append(os.path.join(file_name,files))
                    labels.append(class_name[class_folder])

from google.colab import drive
drive.mount('/content/drive')

output_dir= (r'/content/drive/MyDrive/output')
file_dir =(r'/content/drive/MyDrive/data2017/training2017')
data=pd.read_csv(r'/content/REFERENCE-v0.csv', header=None, names=['id','value'] )
arrange(output_dir,file_dir,data)
print('Success')
label_generation(output_dir)
print('class assigned')